# Generated by Django 3.1.2 on 2020-10-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=100)),
                ('mail_is_real', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
