# Generated by Django 3.1.2 on 2020-10-23 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201023_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 15, 44, 45, 630483, tzinfo=utc)),
        ),
    ]
