# Generated by Django 3.1.2 on 2020-10-26 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201023_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 9, 17, 7, 961926, tzinfo=utc)),
        ),
    ]
