# Generated by Django 3.1.2 on 2020-10-27 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201026_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 12, 31, 27, 565164, tzinfo=utc)),
        ),
    ]
