# Generated by Django 3.1.2 on 2020-11-01 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201028_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 16, 6, 48, 499950, tzinfo=utc)),
        ),
    ]
